name: Build Windows Executable

on:
  workflow_dispatch: # Позволяет запускать процесс сборки вручную по кнопке

jobs:
  build:
    runs-on: windows-latest # Сборка будет происходить в среде Windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Можно указать нужную версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build with PyInstaller
      # Параметр --onefile собирает все в один .exe
      # Параметр --windowed скрывает черную консоль (убери его, если консоль нужна)
      run: pyinstaller --onefile --windowed string-art-generator.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: String-Art-Generator-Windows-Exe
        path: dist/*.exe
